# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jkkim/projects/tsp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jkkim/projects/tsp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jkkim/projects/tsp/CMakeFiles /home/jkkim/projects/tsp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jkkim/projects/tsp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tsp

# Build rule for target.
tsp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsp
.PHONY : tsp

# fast build rule for target.
tsp/fast:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/build
.PHONY : tsp/fast

src/helper/FileHelper.o: src/helper/FileHelper.cpp.o

.PHONY : src/helper/FileHelper.o

# target to build an object file
src/helper/FileHelper.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/helper/FileHelper.cpp.o
.PHONY : src/helper/FileHelper.cpp.o

src/helper/FileHelper.i: src/helper/FileHelper.cpp.i

.PHONY : src/helper/FileHelper.i

# target to preprocess a source file
src/helper/FileHelper.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/helper/FileHelper.cpp.i
.PHONY : src/helper/FileHelper.cpp.i

src/helper/FileHelper.s: src/helper/FileHelper.cpp.s

.PHONY : src/helper/FileHelper.s

# target to generate assembly for a file
src/helper/FileHelper.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/helper/FileHelper.cpp.s
.PHONY : src/helper/FileHelper.cpp.s

src/helper/Timer.o: src/helper/Timer.cpp.o

.PHONY : src/helper/Timer.o

# target to build an object file
src/helper/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/helper/Timer.cpp.o
.PHONY : src/helper/Timer.cpp.o

src/helper/Timer.i: src/helper/Timer.cpp.i

.PHONY : src/helper/Timer.i

# target to preprocess a source file
src/helper/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/helper/Timer.cpp.i
.PHONY : src/helper/Timer.cpp.i

src/helper/Timer.s: src/helper/Timer.cpp.s

.PHONY : src/helper/Timer.s

# target to generate assembly for a file
src/helper/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/helper/Timer.cpp.s
.PHONY : src/helper/Timer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/Graph.o: src/model/Graph.cpp.o

.PHONY : src/model/Graph.o

# target to build an object file
src/model/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/model/Graph.cpp.o
.PHONY : src/model/Graph.cpp.o

src/model/Graph.i: src/model/Graph.cpp.i

.PHONY : src/model/Graph.i

# target to preprocess a source file
src/model/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/model/Graph.cpp.i
.PHONY : src/model/Graph.cpp.i

src/model/Graph.s: src/model/Graph.cpp.s

.PHONY : src/model/Graph.s

# target to generate assembly for a file
src/model/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/model/Graph.cpp.s
.PHONY : src/model/Graph.cpp.s

src/model/Node.o: src/model/Node.cpp.o

.PHONY : src/model/Node.o

# target to build an object file
src/model/Node.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/model/Node.cpp.o
.PHONY : src/model/Node.cpp.o

src/model/Node.i: src/model/Node.cpp.i

.PHONY : src/model/Node.i

# target to preprocess a source file
src/model/Node.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/model/Node.cpp.i
.PHONY : src/model/Node.cpp.i

src/model/Node.s: src/model/Node.cpp.s

.PHONY : src/model/Node.s

# target to generate assembly for a file
src/model/Node.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/model/Node.cpp.s
.PHONY : src/model/Node.cpp.s

src/solver/AbstractSolver.o: src/solver/AbstractSolver.cpp.o

.PHONY : src/solver/AbstractSolver.o

# target to build an object file
src/solver/AbstractSolver.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/AbstractSolver.cpp.o
.PHONY : src/solver/AbstractSolver.cpp.o

src/solver/AbstractSolver.i: src/solver/AbstractSolver.cpp.i

.PHONY : src/solver/AbstractSolver.i

# target to preprocess a source file
src/solver/AbstractSolver.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/AbstractSolver.cpp.i
.PHONY : src/solver/AbstractSolver.cpp.i

src/solver/AbstractSolver.s: src/solver/AbstractSolver.cpp.s

.PHONY : src/solver/AbstractSolver.s

# target to generate assembly for a file
src/solver/AbstractSolver.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/AbstractSolver.cpp.s
.PHONY : src/solver/AbstractSolver.cpp.s

src/solver/BasicHillClimbing.o: src/solver/BasicHillClimbing.cpp.o

.PHONY : src/solver/BasicHillClimbing.o

# target to build an object file
src/solver/BasicHillClimbing.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/BasicHillClimbing.cpp.o
.PHONY : src/solver/BasicHillClimbing.cpp.o

src/solver/BasicHillClimbing.i: src/solver/BasicHillClimbing.cpp.i

.PHONY : src/solver/BasicHillClimbing.i

# target to preprocess a source file
src/solver/BasicHillClimbing.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/BasicHillClimbing.cpp.i
.PHONY : src/solver/BasicHillClimbing.cpp.i

src/solver/BasicHillClimbing.s: src/solver/BasicHillClimbing.cpp.s

.PHONY : src/solver/BasicHillClimbing.s

# target to generate assembly for a file
src/solver/BasicHillClimbing.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/BasicHillClimbing.cpp.s
.PHONY : src/solver/BasicHillClimbing.cpp.s

src/solver/SequentialGreedy.o: src/solver/SequentialGreedy.cpp.o

.PHONY : src/solver/SequentialGreedy.o

# target to build an object file
src/solver/SequentialGreedy.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/SequentialGreedy.cpp.o
.PHONY : src/solver/SequentialGreedy.cpp.o

src/solver/SequentialGreedy.i: src/solver/SequentialGreedy.cpp.i

.PHONY : src/solver/SequentialGreedy.i

# target to preprocess a source file
src/solver/SequentialGreedy.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/SequentialGreedy.cpp.i
.PHONY : src/solver/SequentialGreedy.cpp.i

src/solver/SequentialGreedy.s: src/solver/SequentialGreedy.cpp.s

.PHONY : src/solver/SequentialGreedy.s

# target to generate assembly for a file
src/solver/SequentialGreedy.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/SequentialGreedy.cpp.s
.PHONY : src/solver/SequentialGreedy.cpp.s

src/solver/mapSearchGreedy.o: src/solver/mapSearchGreedy.cpp.o

.PHONY : src/solver/mapSearchGreedy.o

# target to build an object file
src/solver/mapSearchGreedy.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/mapSearchGreedy.cpp.o
.PHONY : src/solver/mapSearchGreedy.cpp.o

src/solver/mapSearchGreedy.i: src/solver/mapSearchGreedy.cpp.i

.PHONY : src/solver/mapSearchGreedy.i

# target to preprocess a source file
src/solver/mapSearchGreedy.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/mapSearchGreedy.cpp.i
.PHONY : src/solver/mapSearchGreedy.cpp.i

src/solver/mapSearchGreedy.s: src/solver/mapSearchGreedy.cpp.s

.PHONY : src/solver/mapSearchGreedy.s

# target to generate assembly for a file
src/solver/mapSearchGreedy.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/mapSearchGreedy.cpp.s
.PHONY : src/solver/mapSearchGreedy.cpp.s

src/solver/tool/Euclidean.o: src/solver/tool/Euclidean.cpp.o

.PHONY : src/solver/tool/Euclidean.o

# target to build an object file
src/solver/tool/Euclidean.cpp.o:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/tool/Euclidean.cpp.o
.PHONY : src/solver/tool/Euclidean.cpp.o

src/solver/tool/Euclidean.i: src/solver/tool/Euclidean.cpp.i

.PHONY : src/solver/tool/Euclidean.i

# target to preprocess a source file
src/solver/tool/Euclidean.cpp.i:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/tool/Euclidean.cpp.i
.PHONY : src/solver/tool/Euclidean.cpp.i

src/solver/tool/Euclidean.s: src/solver/tool/Euclidean.cpp.s

.PHONY : src/solver/tool/Euclidean.s

# target to generate assembly for a file
src/solver/tool/Euclidean.cpp.s:
	$(MAKE) -f CMakeFiles/tsp.dir/build.make CMakeFiles/tsp.dir/src/solver/tool/Euclidean.cpp.s
.PHONY : src/solver/tool/Euclidean.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tsp"
	@echo "... edit_cache"
	@echo "... src/helper/FileHelper.o"
	@echo "... src/helper/FileHelper.i"
	@echo "... src/helper/FileHelper.s"
	@echo "... src/helper/Timer.o"
	@echo "... src/helper/Timer.i"
	@echo "... src/helper/Timer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/Graph.o"
	@echo "... src/model/Graph.i"
	@echo "... src/model/Graph.s"
	@echo "... src/model/Node.o"
	@echo "... src/model/Node.i"
	@echo "... src/model/Node.s"
	@echo "... src/solver/AbstractSolver.o"
	@echo "... src/solver/AbstractSolver.i"
	@echo "... src/solver/AbstractSolver.s"
	@echo "... src/solver/BasicHillClimbing.o"
	@echo "... src/solver/BasicHillClimbing.i"
	@echo "... src/solver/BasicHillClimbing.s"
	@echo "... src/solver/SequentialGreedy.o"
	@echo "... src/solver/SequentialGreedy.i"
	@echo "... src/solver/SequentialGreedy.s"
	@echo "... src/solver/mapSearchGreedy.o"
	@echo "... src/solver/mapSearchGreedy.i"
	@echo "... src/solver/mapSearchGreedy.s"
	@echo "... src/solver/tool/Euclidean.o"
	@echo "... src/solver/tool/Euclidean.i"
	@echo "... src/solver/tool/Euclidean.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

